### ISSUE TITLE
Default value is not applyed to rangebar

### ISSUE THREAD

**Issue by andrecavallari** [IonDen/ion.rangeSlider#197]
I am using a simple
< input type="text" value="50" data-min="0" data-max="100" >

But the bar does not goes to 50 by default...

**Comment by IonDen** [comment]
Hi, should be fixed in 2.0.5. Please check

**Comment by andrecavallari** [comment]
Hi dude, i´ve checked, and still have a bug.. the default values from values array is not getting the index of options.values in chrome, because the splitted values are treated as string, but should be int... so val[0] and val[1] should be surrounded by parseInt() to fix it, look below.

In line 215 and 216...
data.from = val[0] && options.values.indexOf(val[0]);
data.to = val[1] && options.values.indexOf(val[1]);

Should be:
data.from = val[0] && options.values.indexOf(parseInt(val[0]));
data.to = val[1] && options.values.indexOf(parseInt(val[1]));

And thanks again for the fixes, this is the best range plugin ever!!

**Comment by IonDen** [comment]
Hi, no no, they should not.
Values in custom value array could be strings: ["a", "b", "c"]

Look here: http://jsfiddle.net/tu99hc1v/
your example is woking

**Comment by andrecavallari** [comment]
THIS example you show is working...

But try this one... (tried in chrome)
http://jsfiddle.net/tu99hc1v/1/

That´s why the parseInt into the splited values when using values as array...

**Comment by IonDen** [comment]
It is working with abc: http://jsfiddle.net/tu99hc1v/4/
But does not with numbers. I will think about it.

**Comment by andrecavallari** [comment]
I´ve found the solution... will paste here very soon...

**Comment by andrecavallari** [comment]
Yes, the solution:
In line 210...

if (val) {
    val = val.split(";").map(function(value){
        return parseInt(value) ? parseInt(value):value;
    });
}

**Comment by IonDen** [comment]
Yes, i reached the same solution. It will be released tomorrow i think.

**Comment by IonDen** [comment]
Fixed in 2.0.6
