### ISSUE TITLE
Slider maximum is rounded down on certain cases

### ISSUE THREAD

**Issue by megals** [IonDen/ion.rangeSlider#247]
Hi,

The issue is when the max value is say 4.71 and step value is 0.10, then the slider maximum is rounded down to 4.70 and the slider pointer could not be moved further to reach the maximum of 4.71.

i.e the maximum value is rounded down to x.00 for all the slider maximum values ranging from x.01 to x.04 and with the example step value of 0.10.

But the maximum is set correctly for the values ranging from x.05 to x.09. The slider pointer can move up till the maximum without any rounding.

For more detail please refer and compare case 1 and case 3 in the demo 
http://jsfiddle.net/Megala/d8gf0k2t/2/

Could you please check this?

If anything is not clear, please let me know.

Thanks,
Megala

**Comment by megals** [comment]
Thanks for looking into this.
Updated fiddle link http://jsfiddle.net/Megala/d8gf0k2t/4/

**Comment by megals** [comment]
Hi,

Could you please let me know, when this can be fixed?
Thanks for your understanding.

Thanks

**Comment by IonDen** [comment]
Hi, i think next weekend.

**Comment by megals** [comment]
Adding another case of similar rounding issue. 

Say if the slider max is x.29 and the step value is 1, then the slider pointer can reach only up till x instead of x.29.

But it works ok, if the slider max is x.51 and the step value is 1, then the slider pointer can go up to x.51 without any issue.

Thanks.

**Comment by IonDen** [comment]
Yeah, it is the same problem

**Comment by megals** [comment]
Hi,

On further debugging the ion.range.slider.js, the issue is with calcReal function, where it determines the decimal portion of the string. 

            var number = ((max - min) / 100 * percent) + min,
                string = this.options.step.toString().split(".")[1],
                result;

            if (string) {
                number = +number.toFixed(string.length);
            } else {
                number = number / this.options.step;
                number = number * this.options.step;
                number = +number.toFixed(0);
            }

Basically if the step value is 0.05, then the string will be 05. In this situation, the number will be returned with 2 decimal places.

Lets see this case by case to understand it better.

Problem 1:
--------------
If the step value is 0.20 and the number is 4.71

In this case the string will be 2 and the number will be returned with 1 decimal place because length of string is 1. Hence 4.71 is rounded to 1 decimal place resulting 4.7

Problem 2:
--------------
If the step value is 2 and the number is 462.28

In this case the string will be nothing and the number will be returned with 0 decimal place because length of string is 0. Therefore 462.28 is rounded to 0 decimal place resulting 462

Non Problematic case 1:
--------------------------------
If the step value is 0.20 and the number is 4.75

In this case the string will be 2 and the number will be returned with 1 decimal place. Due to rounding to 1 decimal place, the number will be 4.8. Latter in the logic there is condition to check if the number is greater than max. If so, then reset it to max value i.e 4.75

Non Problematic case 2:
--------------------------------
If the step value is 2 and the number is 462.51

In this case the string will be  nothing and the number will be returned with 0 decimal place. Due to rounding to 0 decimal place, the number will be 463. Latter in the logic there is condition to check if the number is greater than max. If so, then reset it to max value i.e 462.51

**********************
Proposed Solution:
**********************
We need to explicitly set number of decimals in the slider options (step_decimals = 2) and that can be used in the statement.
            var number = ((max - min) / 100 * percent) + min,
                string = this.options.step.toFixed(this.options.step_decimals).toString().split(".")[1],
                result;

Please let me know your thoughts.

Thanks,
Megala

**Comment by IonDen** [comment]
Hi, thanks for such a detail review. I will check this on weekend.

**Comment by megals** [comment]
Hi,

Out of curiosity, have you had a chance to look at this issue. It will be greatly helpful, if you could resolve this.

Thanks,
Megala

**Comment by IonDen** [comment]
Hi, i already have fix. But found another bug with grid on negative fractional values. This could take some time.

**Comment by megals** [comment]
Hi,

Just a suggestion, if the bug with grid on negative fraction is not caused by your fix to original issue, can the fix be committed?

Thanks

**Comment by IonDen** [comment]
Hey ok)

**Comment by megals** [comment]
Great. Thanks.

**Comment by IonDen** [comment]
Ok, 2.0.10 is here, please test

**Comment by megals** [comment]
Many thanks. I'm out now. I'll test as soon as I get back.

**Comment by megals** [comment]
Hi,

I have tested with the demo set up http://jsfiddle.net/Megala/d8gf0k2t/6/.

Found it is working for the first entry in the table case a (Slider Max = 4.71 and Slider step = 0.20), but it is still not working for the second entry in the table case b (Slider Max = 462.28 and Slider step = 2)

Also it is not working for the value Slider Max = 4.21 and Slider step = 0.20. Please type this input and test.

Could you check this please?

Thanks.

**Comment by IonDen** [comment]
Hi, yeah, i missed the second entry.

**Comment by megals** [comment]
Np. Can you please fix it and let me know?

Thanks

**Comment by megals** [comment]
Could this issue be looked at any time sooner?

Thanks

**Comment by IonDen** [comment]
I have no time right now, only in few days.

**Comment by megals** [comment]
Thanks. Will really appreciate if this could be looked over the weekend.

**Comment by IonDen** [comment]
Should be fixed in 2.0.11. Please check

**Comment by Romchik** [comment]
http://jsfiddle.net/d8gf0k2t/11/

Hi Denis.

Check the demo from the link above. Focus on the runner with mouse click and use the left/right keys. Rounding error is still present.
Or this is another error?

Regards,
Roman

**Comment by megals** [comment]
Hi Denis,

I checked it and found that it is still not working for the case with Slider Max = 4.21 and Slider step = 0.20 
Could you please check?

Thanks,
Megala

**Comment by IonDen** [comment]
@Romchik moving with keyboard is in beta stage, this is not an error.
@megals ohh, no, i fixed another rounding bug, but not this. I recreated demo: http://jsfiddle.net/IonDen/fu8yc2w6/ will fix in next update.

**Comment by megals** [comment]
Hi Denis,

Could you please let me know, when the next update will be available?

Thanks,
Megala

**Comment by IonDen** [comment]
@megals i will write in this ticket.

**Comment by IonDen** [comment]
Should be fixed in 2.0.12

**Comment by megals** [comment]
Hi Denis,

I will check it now.

Thanks,
Megala

**Comment by megals** [comment]
Thanks Denis. The fix covers all my scenarios.

**Comment by IonDen** [comment]
Nice)
